[package]
name = "rust-learn"
version = "1.0.0"
authors = ["Ryan Dsouza <dsouza.ryan.11@gmail.com>"]
edition = "2018"

[[bin]]
name = "rust-learn"
path = "src/traits.rs"

[dependencies]
rand = "0.7.3"
